function varargout = animatescattereye_qa(rcv_a, N, pausetime, ...
                                       numShifts, action, separation)

error(nargchk(6,6,nargin));
error(nargoutchk(0,2,nargout));

set(0,'ShowHiddenHandles','on');
ss = get(0,'ScreenSize');
set(0,'ShowHiddenHandles','off');
h = [];
h1 = [];
shifts = mod([0 1 2 3 4 3 2 1 0 -1 -2 -3 -4 -3 -2 -1 0]+N,N);
lenshifts = length(shifts);
for idx = [0:numShifts]
    switch(action)
    case 'lr'
        i = shifts(rem(idx,lenshifts)+1);
    case 'lin'
        i = rem(idx,N);
    otherwise
        error('bad value for ACTION');
    end

    ilate = rem(i-separation+N,N);
    iearly = rem(i+separation+N,N);

    h = scatterplot_qa(rcv_a, ...
              1, ...
              0, ...
              'c-', ...
              h);
    fp = get(h,'position');
    set(h,'position',[ss(3)*.01 ss(4)*.01 fp(3) fp(4)])
    hold on;
    if(separation >= 0)
        h = scatterplot_qa(rcv_a, ...
                  N, ...
                  0, ...
                  'k.', ...
                  h);
    end
    h = scatterplot_qa(rcv_a, ...
              N, ...
              i, ...
              'b*', ...
              h);
    if((ilate > 0)&(separation > 0))
        h = scatterplot_qa(rcv_a, ...
                  N, ...
                  ilate, ...
                  'm.', ...
                  h);
    end
    if((iearly > 0)&(separation > 0))
        h = scatterplot_qa(rcv_a, ...
                  N, ...
                  iearly, ...
                  'r.', ...
                  h);
    end
    hold off;
    h1 = eyediagram_qa(rcv_a, ...
              N, ...
              1, ...
              i, ...
              'b-', ...
              h1);
    set(h1,'position',[ss(3)*.99-fp(3) ss(4)*.8-fp(4) fp(3) fp(4)]);
    pause(.01)
end
if(nargout >= 1)
    varargout(1) = {h};
end

if(nargout >= 2)
    varargout(2) = {h1};
end